server:
  port: 8080

security:
  jwt:
    secret: faf82b847cff0bbd37cd3b79751664d868b97c3f05dea0f30f69fb78f2630593

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
        server:
          webflux:
            discovery:
              locator:
                enabled: true
                lower-case-service-id: true
            routes:
              - id: user-service-auth
                uri: lb://user-service
                predicates:
                  - Path=/auth/**
                filters:
                  - StripPrefix=0

              - id: user-service-users
                uri: lb://user-service
                predicates:
                  - Path=/api/users/**
                filters:
                  - StripPrefix=0
                  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info