server:
  port: 8080

security:
  jwt:
    secret: faf82b847cff0bbd37cd3b79751664d868b97c3f05dea0f30f69fb78f2630593

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - http://localhost:5173
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=0

            - id: user-service-users
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=0
            
            - id: user-service-admin
              uri: lb://user-service
              predicates:
                - Path=/api/admin/users/**
              filters:
                - StripPrefix=0

            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/api/books/**
              filters:
                - StripPrefix=0

            - id: loan-service
              uri: lb://loan-service
              predicates:
                - Path=/api/loans/**
              filters:
                - StripPrefix=0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

app:
  internal:
    api-key: ${INTERNAL_API_KEY:zvk93JOJEssmt82kQW+NEYQQFa2CAHUX5Mqnd1mA6yE=}
  auth:
    user-cache-ttl-seconds: 3600
  
